// ABOUTME: Stub for Convex generated API module.
// ABOUTME: Real file is generated by `npx convex dev`; this stub enables testing.

/* eslint-disable @typescript-eslint/no-explicit-any */
export const api: any = new Proxy(
  {},
  {
    get(_target, module: string) {
      return new Proxy(
        {},
        {
          get(_t, fn: string) {
            return `${module}:${fn}`;
          },
        },
      );
    },
  },
);
