// ABOUTME: Stub for Convex generated data model types.
// ABOUTME: Real file is generated by `npx convex dev`; this stub enables testing.

/* eslint-disable @typescript-eslint/no-explicit-any */
export type Id<T extends string> = string & { __tableName: T };
