// ABOUTME: Stub for Convex generated server module.
// ABOUTME: Real file is generated by `npx convex dev`; this stub enables testing.

/* eslint-disable @typescript-eslint/no-explicit-any */
export type DatabaseReader = any;
export function query(config: any) {
  return config;
}
export function mutation(config: any) {
  return config;
}
